version: "3"
networks:
    backend:
        driver: bridge
services:
    api:
        build: .
        ports:
            - "3000:3000"
        depends_on:
            - db
        networks:
            - backend
    db:
        image: postgres:alpine
        restart: always
        env_file:
            - .env
        ports:
            - "5432:5432"
        networks:
            - backend
    adminer:
        image: adminer
        restart: always
        ports:
            - 5001:8080
