version: "3"
services:
    api:
        build: .
        ports:
            - "3000:3000"
        environment:
            PORT: "3000"
    db:
        image: postgres:alpine
        restart: always
        env_file:
            - .env
        ports:
            - "5432:5432"
    adminer:
        image: adminer
        restart: always
        ports:
            - 5001:8080
