version: "3"
services:
  db:
    image: postgres:alpine
    restart: always
    env_file:
      - .env
    environment:
      - PG_HOST="localhost"
      - PG_PORT=${APP_DB_PORT}
      - POSTGRES_USER=${APP_DB_USER}
      - POSTGRES_PASSWORD=${APP_DB_PASSWORD}
      - POSTGRES_DB=${APP_DB_DB}
    ports:
      - 5432:5432
